# Generated by Django 3.1 on 2020-08-29 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_video'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='video',
            table='video',
        ),
    ]
